In [ ]:
import numpy as np
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [ ]:
a2=np.array([[1,2],[3,4]])
a2

array([[1, 2],
       [3, 4]])

In [ ]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[10,11,12],[13,14,15],[16,17,18]]
             ])

In [ ]:
a1.shape


(3,)

In [ ]:
a2.shape


(2, 2)

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [ ]:
a1.size,a2.size,a3.size,

(3, 4, 18)

In [ ]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [ ]:
ones=np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

dtype('float64')

In [ ]:
type(ones)

numpy.ndarray

In [ ]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [ ]:
np.random.seed(4)
x=np.random.randint(0,10,size=(3,5))
x

array([[7, 5, 1, 8, 7],
       [8, 2, 9, 7, 7],
       [7, 9, 8, 4, 2]])

In [ ]:
x.shape

(3, 5)

In [ ]:
x.size

15

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [ ]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 0, 5, 0, 9],
         [5, 7, 5, 9, 8],
         [2, 4, 2, 3, 0],
         [3, 6, 9, 0, 3]],

        [[4, 8, 6, 3, 7],
         [3, 9, 1, 4, 8],
         [3, 0, 2, 4, 6],
         [1, 9, 0, 9, 3]],

        [[1, 2, 3, 2, 9],
         [5, 2, 7, 9, 5],
         [6, 5, 9, 9, 6],
         [8, 5, 4, 4, 6]]],


       [[[2, 2, 1, 3, 7],
         [4, 0, 5, 7, 3],
         [8, 5, 9, 1, 5],
         [4, 3, 9, 5, 6]],

        [[6, 1, 0, 5, 2],
         [0, 5, 8, 5, 7],
         [8, 9, 9, 0, 3],
         [7, 0, 4, 7, 7]],

        [[4, 1, 3, 0, 7],
         [7, 5, 1, 5, 3],
         [9, 3, 0, 9, 7],
         [6, 1, 7, 9, 6]]]])

In [ ]:
a4[ : , : , : , :3]

array([[[[3, 0, 5],
         [5, 7, 5],
         [2, 4, 2],
         [3, 6, 9]],

        [[4, 8, 6],
         [3, 9, 1],
         [3, 0, 2],
         [1, 9, 0]],

        [[1, 2, 3],
         [5, 2, 7],
         [6, 5, 9],
         [8, 5, 4]]],


       [[[2, 2, 1],
         [4, 0, 5],
         [8, 5, 9],
         [4, 3, 9]],

        [[6, 1, 0],
         [0, 5, 8],
         [8, 9, 9],
         [7, 0, 4]],

        [[4, 1, 3],
         [7, 5, 1],
         [9, 3, 0],
         [6, 1, 7]]]])

In [ ]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [ ]:
arr+ones

array([2., 3., 4.])

In [ ]:
arr*ones

array([1., 2., 3.])

In [ ]:
arrTwo=np.array([[1,2,3],[2,3,4]])
arrTwo

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arrTwo+ones

array([[2., 3., 4.],
       [3., 4., 5.]])

In [ ]:
arrTwo+arr

array([[2, 4, 6],
       [3, 5, 7]])

In [ ]:
arr

array([1, 2, 3])

In [ ]:
arr/2

array([0.5, 1. , 1.5])

In [ ]:
arr%2

array([1, 0, 1])

In [ ]:
type(ones)

numpy.ndarray

In [ ]:
ones

array([1., 1., 1.])

In [ ]:
li=[1,2,3]
type(li)

list

In [ ]:
sum(li)

6

In [ ]:
sum(ones)

3.0

In [ ]:
np.sum(ones)

3.0

In [ ]:
arr

array([1, 2, 3])

In [ ]:
np.std(arr)

0.816496580927726

In [ ]:
np.var(arr)

0.6666666666666666

In [ ]:
np.sqrt(np.var(arr))

0.816496580927726